### ISSUE TITLE
im视频通话报错

### ISSUE THREAD

**Issue by 1WallE** [tencentyun/TUICalling#22]
https://user-images.githubusercontent.com/84114133/153139458-328e9b09-717c-418b-b175-2606bf3de181.mp4
im视频通话报错：trtc_api Calling - CallAction_Cancel cancel failed, code: 8010 desc: inviteID invalid or invitation has been processed

**Comment by 1WallE** [comment]
sdkappid: 1400602041
roomid:
userid:
时间点：2022年2月9日3时2分左右
版本信息：5.7.1435

**Comment by MinTate** [comment]
sdkappid错误，已修改~
