### ISSUE TITLE
安卓端推到后台就没法收到呼叫呢

### ISSUE THREAD

**Issue by LxzBUG** [tencentyun/TUICalling#23]
测试手机：小米

**Comment by reneechai** [comment]
> 测试手机：小米
当前版本已经支持后台接收呼叫。
问题排查：
1、请先升级版本到最新，如升级体量较大，可查看TRTCCalling.java中isAppRunningForeground()方法调用处，按照demo进行修改。 ——建议升级到最新版本，便于后续升级及维护。
2、检查手机的权限，由于厂商定制，Android手机需要开启“悬浮窗权限”或者“后台弹出界面”权限。——权限问题可联系我们做兼容处理（麻烦提供手机型号及Android版本，例如：小米10 Android 11）
感谢关注~
