### ISSUE TITLE
关于离线推送

### ISSUE THREAD

**Issue by foxstudiohua** [tencentyun/TUICalling#26]
新版demo里面TPNS推送部分还是和旧版一样，使用V2TIMAPNSConfig向V2TIMManager设置APNS。但网页上TPNS的控制台已经没有上传证书获取sdkBusiId的入口了，请问该如何获取sdkBusiId？

**Comment by Tencent-Alice** [comment]
您好  根据您的问题 请问您是集成的旧版本吗   以这个为例： 用户自己到苹果注册开发者证书，在开发者帐号中下载并生成证书(p12 文件)，将生成的 p12 文件传到腾讯证书管理控制台，控制台会自动生成一个证书 ID，将证书 ID 传入一下 busiID 参数中 。技术问题 欢迎交流 Q2562367495 注明来意

**Comment by foxstudiohua** [comment]
昨天已经通过客服解决了，你们的demo直接照抄了旧版的注释。实际情况是，集成TPNS推送时，这个id传0。demo和网页文档更新都偏慢一拍。

**Comment by Tencent-Alice** [comment]
您好，问题解决就好，感谢您的反馈和指正
祝您生活愉快
