### ISSUE TITLE
音视频的卡顿，跳帧，画面模糊，已经当前网络状态丢包，延时，抖动在SDK层能打开debug日志看到不？

### ISSUE THREAD

**Issue by janksenhu** [tencentyun/TUICalling#4]
音视频的卡顿，跳帧，画面模糊，已经当前网络状态丢包，延时，抖动在SDK层能打开debug日志看到不？

**Comment by MinTate** [comment]
在腾讯云控制台：https://console.cloud.tencent.com/trtc/monitor，可以看到类似状态~
