### ISSUE TITLE
TRTC_Android

### ISSUE THREAD

**Issue by trycatchx** [tencentyun/TUICalling#40]
请问本工程 和 [TRTC_Android](https://github.com/LiteAVSDK/TRTC_Android )这个区别是什么？

**Comment by MinTate** [comment]
这是在TRTC基础上封装的通话的场景化解决方案，可以看一下我们官网，就是这样的区别：
![image](https://user-images.githubusercontent.com/16069375/167085036-21f9f045-7174-4f22-a84d-d818c1a473b6.png)
